### ISSUE TITLE
Confused about how to calculate the percentage of annotations used during training.

### ISSUE THREAD

**Issue by Supgb** [yk-pku/Two-shot-Video-Object-Segmentation#10]
Thank you for your excellent work! 👍🏻

However, I am confused by **the percentages such as 7.3% and 2.9%** that appear in the paper. I would appreciate it if you could explain how you derived these numbers.

**Comment by yk-pku** [comment]
The ratio of training data (frames) used in 2-shot to the total training data for each dataset.
