### ISSUE TITLE
how yv_rand_2frames.json is generated?

### ISSUE THREAD

**Issue by zz-zzu** [yk-pku/Two-shot-Video-Object-Segmentation#11]
It's an excellent work, thanks for your code! However, I have a question: how yv_rand_2frames.json is generated?  Could you please tell me how to generate this file? Currently, I'm unsure of the best method to generate it for my own data. Do you have any recommendations?

**Comment by yk-pku** [comment]
Thanks. You can just randomly select two frames per video.
