### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../YouTube/phase2/yv_gt_480p'

### ISSUE THREAD

**Issue by hayleeXinyi** [yk-pku/Two-shot-Video-Object-Segmentation#3]
Did I miss something? When I finished training for Stage 1 and then performed Stage 2.

**Comment by hayleeXinyi** [comment]
Should I copy the data from “YouTube/train_480p/Annotations” to “YouTube/phase2/yv_gt_480p”?

**Comment by hayleeXinyi** [comment]
That error was generated when I ran the following command

`sh run_youtube_phase2/run_eval_youtube_phase2_left.sh`

**Comment by yk-pku** [comment]
> That error was generated when I ran the following command
> 
> `sh run_youtube_phase2/run_eval_youtube_phase2_left.sh`

You need to create the yv_gt_480p folder first.

**Comment by hayleeXinyi** [comment]
So I need to create the yv_gt_480p folder first and then find the corresponding GTs based on davis_rand_2frames.json and yv_rand_2frames.json and save it in the yv_gt_480p folder?

**Comment by hayleeXinyi** [comment]
Can I find the GTs based only on davis_rand_2frames.json and yv_rand_2frames.json? There is further filtering in the renew_vos_loader in the phase 1 training, will it affect?
Can you kindly provide the official code or results? It would be good to avoid misunderstandings leading to reproduction errors.

**Comment by yk-pku** [comment]
> So I need to create the yv_gt_480p folder first and then find the corresponding GTs based on davis_rand_2frames.json and yv_rand_2frames.json and save it in the yv_gt_480p folder?

Yes

**Comment by yk-pku** [comment]
> Can I find the GTs based only on davis_rand_2frames.json and yv_rand_2frames.json? There is further filtering in the renew_vos_loader in the phase 1 training, will it affect? Can you kindly provide the official code or results? It would be good to avoid misunderstandings leading to reproduction errors.
xx_rand_2frames.json only contains the GTs we used, you don't need further filtering, and this is the official code.

**Comment by hayleeXinyi** [comment]
Now I have met this trouble. (after I solve the problem of yv_gt_480p.)

![image](https://github.com/yk-pku/Two-shot-Video-Object-Segmentation/assets/111858371/5f436d7e-515c-4100-9f31-e6dfa5a8d35a)

![image](https://github.com/yk-pku/Two-shot-Video-Object-Segmentation/assets/111858371/2674b061-1051-4c6b-8d22-3d6bf0a7d96e)

stacks
![image](https://github.com/yk-pku/Two-shot-Video-Object-Segmentation/assets/111858371/b6288626-bbfe-4fc2-898a-771e5028e7d0)

**Comment by yk-pku** [comment]
Did this error occurred when you run bidirectional inference ?

**Comment by yk-pku** [comment]
Did this error occur when you run bidirectional inference?

**Comment by hayleeXinyi** [comment]
Found the bug, it was due to the first reference frame not having a label. How do you expect this situation to be handled?

**Comment by yk-pku** [comment]
> Found the bug, it was due to the first reference frame not having a label. How do you expect this situation to be handled?

Yes, exactly. I checked my local data, I just discard the gt frames that have no labels.

**Comment by yk-pku** [comment]
No, the video that has no pseudo label will be not participated in phase-2.

**Comment by hayleeXinyi** [comment]
Understood, is it convenient to ask the number of videos involved in the second phase of training?

**Comment by yk-pku** [comment]
> Understood, is it convenient to ask the number of videos involved in the second phase of training?

3458 videos in YouTube-VOS

**Comment by yk-pku** [comment]
Please open another issue if you have any other questions, as this issue is too long and its content is beyond the topic.
