### ISSUE TITLE
How to verify the effect of the model based on Youtube 2019 validate?

### ISSUE THREAD

**Issue by hayleeXinyi** [yk-pku/Two-shot-Video-Object-Segmentation#4]
Hi, I have successfully run through all the phases, I found only predicted masks for validation, no quantified results. The ground truth are not included in the test dataset of “Youtube 2019“(like Youtube/validate) and ”Davis“. I tried to find the submission interface in the competition but didn't find it, how can I get the quantified results in the test dataset?

**Comment by yk-pku** [comment]
You can submit your results via this link: https://youtube-vos.org/dataset/vos/

**Comment by hayleeXinyi** [comment]
Thanks a lot. I got the result now and may have accessed the wrong old server before😂.
