### ISSUE TITLE
Could not find GT in stage 1 with own data set

### ISSUE THREAD

**Issue by hayleeXinyi** [yk-pku/Two-shot-Video-Object-Segmentation#5]
When I try to use my own dataset, in the first stage, I find that when I get the semi-data, the code tries to find annotations corresponding to files other than those mentioned in xx_rand_2frames.
![image](https://github.com/yk-pku/Two-shot-Video-Object-Segmentation/assets/111858371/01340299-4037-4804-81a0-22947f0909cc)
But why do I need annotations for images other than the two frames?

**Comment by yk-pku** [comment]
Sorry, I did not really get your means.  If your question is why the dataset still needs to get GTs for all images, my answer is I don't want to change the format of the original VOS dataset, and I don't want to change the codes of STCN too much.

**Comment by yk-pku** [comment]
> I only have two frames of labelled data in my dataset, so this code cannot find the corresponding ground truth for the unlabeled data when I run it. Actually, I'm just wondering if the ground truth of the frames, which are not mentioned in xx_rand_2frames, is being used.

If you read the codes carefully, then you can find I didn't use any GTs beyond 2-frames.json. I use the mask_gt to indicate whether the frame is with the gt during training.

**Comment by yk-pku** [comment]
> Private datasets face the problem of very little annotation, I think this paper is good to help solve this problem🙏, but compatibility with other datasets in the code is troublesome😭. One is the problem of error reporting now (the code expects to find the ground truth of unannotated data) and the code for intermediate inference relies too strongly on youtube and Davis.

Sorry for that. I did not expect the codes for other datasets. If you want to deploy this code elsewhere, you need to modify it yourself.

**Comment by hayleeXinyi** [comment]
> > I only have two frames of labelled data in my dataset, so this code cannot find the corresponding ground truth for the unlabeled data when I run it. Actually, I'm just wondering if the ground truth of the frames, which are not mentioned in xx_rand_2frames, is being used.
> 
> If you read the codes carefully, then you can find I didn't use any GTs beyond 2-frames.json. I use the mask_gt to indicate whether the frame is with the gt during training.

Thanks. But I am still confused, could you tell me what "value or mask" is used with the inferred mask to calculate the loss of unlabelled frames?

**Comment by yk-pku** [comment]
> 

Sorry, I did not follow what you meant. But I guess if you understand this [part](https://github.com/yk-pku/Two-shot-Video-Object-Segmentation/blob/a2170e2115b854067d5f7a5d427d2f44a40d787c/model/model.py#L26) of codes, you should get answers.
