### ISSUE TITLE
Confused about the update_pseudo_bank parameter

### ISSUE THREAD

**Issue by hayleeXinyi** [yk-pku/Two-shot-Video-Object-Segmentation#8]
Does update_pseudo_bank need to be set to 0 for phase 2 training? Readme doesn't show a setting for this parameter.

**Comment by yk-pku** [comment]
update_pseudo_bank = 0 means the model will change the original masks of phase-1. We found the performance of the current setting is already saturated for VOS benchmarks, therefore, you can leave this parameter as its default value.
