### ISSUE TITLE
error when run "sh run_youtube_phase2/run_eval_youtube_phase2_left.sh"  

### ISSUE THREAD

**Issue by jiaxi0030** [yk-pku/Two-shot-Video-Object-Segmentation#9]
![image](https://github.com/yk-pku/Two-shot-Video-Object-Segmentation/assets/92349729/57c7a09d-d809-49f4-acc9-a5e7f4b460e9)
First of all, thank you so much for this awesome package!
But, when generating predictions for the intermediate stages of YouTube, the following problem occurred.

**Comment by yk-pku** [comment]
You need to remove all GTs with no labels first.

**Comment by jiaxi0030** [comment]
thank you
